# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d0274d89f70217dd468e4d113843a228e06413d7308c4da9fe5b22058e2326bef32b8866fa5c1e5255cf81e8e42a9fd37f8a382497701d83c38cf33f83c07949

test:
  secret_key_base: 1e39d299b34ac2d79d26769e9e7f46f37918678941f09a7b801187ee73e82a1647182ceb3da95a35982aa8bb0ab6d48589b86007ae724d278cf671472e20738c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
